name: foody.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd frontend
        npm i --legacy-peer-deps
    - name: Backend setup
      run: |
        npm i
      working-directory: backend
    - name: Build
      run: |
        export NODE_OPTIONS=--max-old-space-size=4096
        export GENERATE_SOURCEMAP=false
        npm run build
        
